package controller;

import javafx.event.ActionEvent;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.*;
import javafx.stage.Stage;
import model.InHouse;
import model.Inventory;
import model.Outsourced;
import model.Part;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

/** This is the controller class for the ModifyPart FXML document and not meant to be instantiated.
 * The class is initially passed a Part object from the Inventory Main Screen and uses that to populate the text
 * fields with the object's associated data fields. The user can then update those values and create a new
 * Part object, which replaces the passed Part in the static observable list of Parts in the Inventory.
 * @author Greg Farrell
 * @version 1.0
 * */
public class ModifyPartScreenController implements Initializable {

    /** Radio button setting the InHouse class. */
    public RadioButton inHouseRadioButton;
    /** Radio button setting the Outsourced class. */
    public RadioButton outSourcedRadioButton;
    /** Toggle group linking the inHouseRadioButton and outSourcedRadioButton. */
    public ToggleGroup modifyPartToggle;
    /** Radio button label, changes depending on which button is selected. */
    public Label radioButtonLabel;
    /** Disabled text field for the part ID, which is autogenerated. */
    public TextField idTextField;
    /** Part name text field. */
    public TextField nameTextField;
    /** Part maximum text field. */
    public TextField maxTextField;
    /** Part minimum text field. */
    public TextField minTextField;
    /** Part stock text field. */
    public TextField inventoryTextField;
    /** Part price text field. */
    public TextField priceTextField;
    /** Machine ID or Company Name text field depending on which radio button is selected. */
    public TextField radioButtonTextField;

    /** Static Part member used to receive a Part object passed from the Inventory Main Screen */
    public static Part tempPart = null;
    /** Static int member used to store the static Part member's index in the static observable list in the Inventory class */
    public static int tempPartIndex;
    private static boolean isInHouse;
    private static String radioInfo1;
    private static String radioInfo2;

    /** This method is called by the FXMLLoader.load() call contained in the toModifyPart() method of the InventoryMainScreeController class.
     * The method initializes two static fields as empty so that they can be utilized to pass data between the
     * radioButtonTextField depending on which radio button is selected. The method also takes the static part that was
     * passed from the Inventory Main Screen and uses it to populate the various text fields.
     * @param resourceBundle An unreferenced ResourceBundle object passed automatically
     * @param url An unreferenced URL object passed automatically
     * */
    @Override
    public void initialize(URL url, ResourceBundle resourceBundle) {
        radioInfo1 = "";
        radioInfo2 = "";
        idTextField.setText(String.valueOf(tempPart.getId()));
        nameTextField.setText(tempPart.getName());
        inventoryTextField.setText(String.valueOf(tempPart.getStock()));
        priceTextField.setText(String.valueOf(tempPart.getPrice()));
        minTextField.setText(String.valueOf(tempPart.getMin()));
        maxTextField.setText(String.valueOf(tempPart.getMax()));

        if (tempPart instanceof InHouse) {
            inHouseRadioButton.setSelected(true);
            radioButtonLabel.setText("Machine ID:");
            radioButtonTextField.setText(String.valueOf(((InHouse) tempPart).getMachineId()));
            isInHouse = true;
            radioInfo1 = String.valueOf(((InHouse) tempPart).getMachineId());
        }
        else {
            outSourcedRadioButton.setSelected(true);
            radioButtonLabel.setText("Company Name:");
            radioButtonTextField.setText(String.valueOf(((Outsourced) tempPart).getCompanyName()));
            isInHouse = false;
            radioInfo2 = String.valueOf(((Outsourced) tempPart).getCompanyName());
        }
    }

    /** This method is an event handler for the Cancel button that sends the program back to the main screen.
     * The method loads the FXML document for the main inventory screen, passes that to a new scene and then sets the
     * stage with the new scene.
     * @param actionEvent Passed from the On Action event listener in the ModifyPartScreen FXML document
     * @throws IOException The FXMLLoader.load() call will throw this exception if the FXML document can't be found.
     */
    public void backToMain(ActionEvent actionEvent) throws IOException {

        Parent root = FXMLLoader.load(getClass().getResource("/view/InventoryMainScreen.fxml"));
        Stage stage = (Stage) ((Node) actionEvent.getSource()).getScene().getWindow();
        Scene scene = new Scene(root, 800, 600);
        stage.setTitle("Inventory Main Screen");
        stage.setScene(scene);
        stage.show();
    }

    /** This method is an event handler for the inHouseRadio Button that sets the radioButtonLabel to "Machine ID: "
     *  The method also grabs the text from the radioButtonTextField and makes a copy of it that is used to repopulate
     *  the text field if the radio button gets toggled back, so the user doesn't need to reenter it.
     * @param actionEvent Passed from the On Action event listener in the ModifyPartScreen FXML document
     */
    public void inHouseMachineId(ActionEvent actionEvent) {
        radioButtonLabel.setText("Machine ID:");

        if (!isInHouse && radioInfo1.isEmpty()) {
            radioInfo2 = radioButtonTextField.getText();
            radioButtonTextField.clear();
        }
        else {
            radioInfo2 = radioButtonTextField.getText();
            radioButtonTextField.setText(radioInfo1);
        }
    }

    /** This method is an event handler for the outSourcedRadio Button that sets the radioButtonLabel to "Company Name: "
     *  The method also grabs the text from the radioButtonTextField and makes a copy of it that is used to repopulate
     *  the text field if the radio button gets toggled back so the user doesn't need to reenter it.
     * @param actionEvent Passed from the On Action event listener in the ModifyPartScreen FXML document
     */
    public void outSourcedCompanyName(ActionEvent actionEvent) {
        radioButtonLabel.setText("Company Name:");

        if (isInHouse && radioInfo2.isEmpty()) {
            radioInfo1 = radioButtonTextField.getText();
            radioButtonTextField.clear();
        }
        else {
            radioInfo1 = radioButtonTextField.getText();
            radioButtonTextField.setText(radioInfo2);
        }
    }

    /** This method creates a new part object and then adds the part to the static observable list in the Inventory class.
     * The method grabs the data entered in the various text fields and then calls the appropriate constructor, depending
     * on which radio button is selected for InHouse vs OutSourced. There are also validation checks and exception
     * handling to ensure that the data entered are of the appropriate types and adhere various logical rules.
     * @param actionEvent Passed from the On Action event listener in the AddPartScreen FXML document
     * @see InHouse#InHouse(int, String, double, int, int, int, int)
     * @see Outsourced#Outsourced(int, String, double, int, int, int, String)
     * */
    public void savePart(ActionEvent actionEvent) {
        int id;
        String companyName;
        String name;
        double price;
        int stock;
        int min;
        int max;
        int machineID;

        try {
            if (inHouseRadioButton.isSelected()) {

                id = tempPart.getId();
                name = nameTextField.getText();
                price = Double.parseDouble(priceTextField.getText());
                stock = Integer.parseInt(inventoryTextField.getText());
                min = Integer.parseInt(minTextField.getText());
                max = Integer.parseInt(maxTextField.getText());
                machineID = Integer.parseInt(radioButtonTextField.getText());

                if (min > max) {
                    Alert alert = new Alert(Alert.AlertType.ERROR);
                    alert.setTitle("Invalid Input");
                    alert.setContentText("Minimum must be less than or equal to Maximum.");
                    alert.show();
                    return;
                }

                if ((min > stock) || (stock > max)) {
                    Alert alert = new Alert(Alert.AlertType.ERROR);
                    alert.setTitle("Invalid Input");
                    alert.setContentText("Inventory must be between Minimum and Maximum.");
                    alert.show();
                    return;
                }
                String tempText = radioButtonTextField.getText();
                if (tempText.isEmpty()) {
                    Alert alert = new Alert(Alert.AlertType.ERROR);
                    alert.setTitle("Blank Field");
                    alert.setContentText("A Machine ID must be entered.");
                    alert.show();
                    return;
                }

                //machineID = Integer.parseInt(radioButtonTextField.getText());
                System.out.println(name.getClass());
                Part newPart = new InHouse(id, name, price, stock, min, max, machineID);
                Inventory.getAllParts().set(tempPartIndex, newPart);

            } else {

                id = tempPart.getId();
                name = nameTextField.getText();
                if (name.isEmpty()) {
                    Alert alert = new Alert(Alert.AlertType.ERROR);
                    alert.setTitle("No Part Name Entered");
                    alert.setContentText("Please enter a valid part name before saving.");
                    alert.show();
                    return;
                }
                if (!(name.getClass().isInstance("String"))) {
                    System.out.println("Hurray");
                    return;
                }
                price = Double.parseDouble(priceTextField.getText());
                stock = Integer.parseInt(inventoryTextField.getText());
                min = Integer.parseInt(minTextField.getText());
                max = Integer.parseInt(maxTextField.getText());
                companyName = radioButtonTextField.getText();

                if (min > max) {
                    Alert alert = new Alert(Alert.AlertType.ERROR);
                    alert.setTitle("Invalid Input");
                    alert.setContentText("Minimum must be less than or equal to Maximum.");
                    alert.show();
                    return;
                }

                if ((min > stock) || (stock > max)) {
                    Alert alert = new Alert(Alert.AlertType.ERROR);
                    alert.setTitle("Invalid Input");
                    alert.setContentText("Inventory must be between Minimum and Maximum.");
                    alert.show();
                    return;
                }

                String tempText = radioButtonTextField.getText();
                if (tempText.isEmpty()) {
                    Alert alert = new Alert(Alert.AlertType.ERROR);
                    alert.setTitle("Blank Field");
                    alert.setContentText("A Company name must be entered.");
                    alert.show();
                    return;
                }

                //companyName = radioButtonTextField.getText();

                Part newPart = new Outsourced(id, name, price, stock, min, max, companyName);
                Inventory.updatePart(tempPartIndex, newPart);
            }

            Parent root = FXMLLoader.load(getClass().getResource("/view/InventoryMainScreen.fxml"));
            Stage stage = (Stage) ((Node) actionEvent.getSource()).getScene().getWindow();
            Scene scene = new Scene(root, 800, 600);
            stage.setTitle("Inventory Main Screen");
            stage.setScene(scene);
            stage.show();

        }
        catch (NumberFormatException | IOException exception) {
            Alert alert = new Alert(Alert.AlertType.ERROR, "Please enter valid values in the input fields");
            alert.setTitle("Invalid Input Type");
            alert.setContentText(exception.getMessage());
            alert.show();

            System.out.println(exception.getMessage().getClass());
        }
    }
}
